version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: photodump-desktop
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: photodump
    volumes:
      - ./mysql-data:/var/lib/mysql
